name: Build-Kandosh-V7
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: ${{ github.workspace }}/theos
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $THEOS
          rm -rf $THEOS/sdks
          git clone https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build
        run: |
          make FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kandosh-Dylib
          path: "./obj/*.dylib"
